import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css'
import '../../styles/menu.css'
import '../../styles/theme.css'
import '../../styles/responsive-menu.css'
import '../../styles/custom-spacing.css'
import { FreelancerProvider } from '../../context/MarketPlace'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <FreelancerProvider>
      <body>
        {children}
      </body>
      </FreelancerProvider>

    </html>
  )
}
